{{- if .Values.discovery.enabled }}
{{- $fullname := include "library-chart.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: "discoverable-{{ $fullname }}"
  annotations:
    onyxia/discovery: "mongodb"
type: Opaque
data:
  mongodb-service: {{ (include "mongoList" .)  | b64enc | quote }}
  mongodb-name: {{ printf "%s" $fullname | b64enc | quote }}
  {{- if .Values.mongodb.auth.password  }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.username  }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.database  }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.rootPassword  }}
  mongodb-rootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  {{- end }}

{{- end -}}
