{{- if .Values.discovery.enabled }}
{{- $fullname := include "common.names.fullname" .Subcharts.kafka -}}
apiVersion: v1
kind: Secret
metadata:
  name: "discoverable-{{ $fullname }}"
  annotations:
    onyxia/discovery: "kafka"
type: Opaque
data:
  kafka-service: {{ (printf "%s:%d" $fullname (.Values.kafka.service.ports.client | int)) | b64enc | quote }}
{{- end -}}