{{- if .Values.discovery.enabled }}
{{- $fullname := (include "library-chart.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "discoverable-{{ $fullname }}"
  annotations:
    onyxia/discovery: "hive"
type: Opaque
data:
  hive-service: {{ (include "library-chart.fullname" .) | b64enc | quote }}
  hive-endpoint: {{ .Values.s3.endpoint | default ".Values.s3.endpoint"  | b64enc | quote }}
{{- end -}}
