mariadb:
  image:
    tag: "11.5.2"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: ""
    database: my_database
    username: ""
    password: ""
    existingSecret: ""
  volumePermissions:
    enabled: true
  primary:
    existingConfigmap: ""
    resources:
      limits: {}
      requests:
        memory: 512Mi
        cpu: 1000m
    service:
      ports:
        mysql: 3306

discoverable:
  allow: true

