mongodb:
  resources: 
    limits:
      cpu: 100m
      memory: 512Mi
  fullnameOverride: mongodb
  architecture: replicaset
  image:
    tag: "4.4"
  auth:
    rootPassword: changeme
    username: username
    password: changeme
    database: defaultdb
  containerPorts:
    mongodb: 27017
  replicaCount: 2
  discoverable:
    allow: true
fullnameOverride: mongodb
security:
  networkPolicy: 
    enabled: true
