{{- if .Values.ingress.enabled -}}
{{- $fullName := include "opensearch.serviceName" .Subcharts.opensearch -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "opensearch.labels" .Subcharts.opensearch | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- include "opensearch.ingress.annotations" . | nindent 4 }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "opensearch.ingress.supportsIngressClassName" .Subcharts.opensearch)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
    {{- if .Values.ingress.useCertManager }}
      secretName: tls-cert-{{ $fullName }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ .Values.opensearch.httpPort }}
{{- end }}
