{{- if .Values.security.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "opensearch.fullname" .Subcharts.opensearch }}
spec:
  podSelector:
    matchLabels:
      {{- include "opensearch.selectorLabels" .Subcharts.opensearch | nindent 6 }}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress
{{- end }}