{{- if .Values.security.networkPolicy.enabled -}}
{{- if .Values.ingress.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "opensearch.fullname" .Subcharts.opensearch }}-2
spec:
  podSelector:
    matchLabels:
      {{- include "opensearch.selectorLabels" .Subcharts.opensearch | nindent 6 }}
  ingress:
  - from:
    {{- toYaml .Values.security.networkPolicy.from | nindent 4 }}
  policyTypes:
  - Ingress
{{- end }}
{{- end }}