{{- if or .Values.discovery.postgres .Values.discovery.mariadb .Values.discovery.trino  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels: 
    {{- include "library-chart.labels" . | nindent 4 }}
stringData:
  data-sources.json: |-
    {{- include "discovery.secret" . | nindent 4 }}
{{- end }}