apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "library-chart.fullname" . }}-test-connection"
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['http{{ if $.Values.ingress.tls }}s{{ end }}://{{ .Values.ingress.hostname }}']
  restartPolicy: Never
