{{- if .Values.discovery.enabled }}
{{- $fullname := include "library-chart.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: "discoverable-{{ $fullname }}"
  annotations:
    onyxia/discovery: "spark-thrift-server"
type: Opaque
data:
  thrift-service: {{ printf "%s" $fullname | b64enc | quote }}
  thrift-port: {{ print .Values.networking.port | b64enc | quote }}
{{- end -}}
